server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Custom Configuration
auto-builder:
  modules:
    - name: "io:nop.labor"
      root-path: ""
      artifact-id: "labor-tracking"